---
title: "GLMM Resources"
---

We will be running a series of talks, workshops and discussions about generalised linear mixed models (GLMM). This page will collate links and resources.

<span class="red mm">m</span>
<span class="orange mm">m</span>
<span class="yellow mm">m</span>
<span class="green mm">m</span>
<span class="blue mm">m</span>
<span class="brown mm">m</span>
<span class="red mm">m</span>
<span class="orange mm">m</span>
<span class="yellow mm">m</span>
<span class="green mm">m</span>
<span class="blue mm">m</span>
<span class="brown mm">m</span>

## Schedule

All sessions will be 16:00 to 17:00 via [Zoom](https://uofglasgow.zoom.us/j/94098494960)

* 2021-11-03 A Gentle Introduction to Generalized Linear Mixed Models
* 2021-11-17 Generalized Linear Mixed Models for RT data
* 2021-11-24 Pushback against GLMMs ([Gomila, 2021](https://doi.org/10.1037/xge0000920); [Knief & Forstmeier, 2021](https://doi.org/10.3758/s13428-021-01587-5); [Ryan, Evers & Moore, 2021](https://doi.org/10.1525/collabra.27242)

## Resources

* [Learning Statistical Models Through Simulation in R](https://psyteachr.github.io/stat-models-v1/)
* Gomila, R. (2021). Logistic or linear? Estimating causal effects of experimental treatments on binary outcomes using regression analysis. Journal of Experimental Psychology: General, 150(4), 700–709. [DOI: 10.1037/xge0000920](https://doi.org/10.1037/xge0000920)
* Knief U, Forstmeier W. (2021). Violating the normality assumption may be the lesser of two evils. Behav Res Methods. [DOI: 10.3758/s13428-021-01587-5](https://doi.org/10.3758/s13428-021-01587-5)
* William H. Ryan, Ellen R. K. Evers, Don A. Moore; Poisson Regressions: A Little Fishy. Collabra: Psychology 4 January 2021; 7 (1): 27242. [DOI: 10.1525/collabra.27242](https://doi.org/10.1525/collabra.27242)
